### ISSUE TITLE
Missing info.json and answer_vocab.json in prediction

### ISSUE THREAD

**Issue by fereenwong** [matthewdm0816/BridgeQA#2]
First of all, thank you for sharing your code and work with the community. I really appreciate your contribution.

I've encountered an issue while trying to run `predict.py`. It seems that two essential files are missing from the repository:

1. info.json
2. answer_vocab.json

These files appear to be required for the script to run successfully. Could you please provide these files or instructions on how to generate them?

Thank you for your time and assistance.

**Comment by matthewdm0816** [comment]
Hi, thank you for your focus and recognition on our work. Normally `info.json` and `answer_vocab.json` are generated along with training procedure (same directory to store the model checkpoints), and records model arguments and answer vocabulary respectively. For the pretrained model we provided, I'll upload these related files as soon as I'm able to access them.

**Comment by matthewdm0816** [comment]
Hi, the config file is uploaded at [Google Drive](https://drive.google.com/drive/folders/1KxF1a0sNxHADvp0VXkQduZ25cth6gV6i?usp=drive_link). Please first replace the corresponding i2t file and 2D view location in it.
Also, please use the newest code, as we fixed a bug on the BLIP config file location.

**Comment by fereenwong** [comment]
@matthewdm0816 Thanks a lot for the timely reply. Problem solved.
