### ISSUE TITLE
ScanNet Instructions and GLoVE embedding

### ISSUE THREAD

**Issue by xiaoxinning** [matthewdm0816/BridgeQA#5]
thanks for your releasing code, but I cam't open the link about ScanNet Instructions and GLoVE embedding

**Comment by matthewdm0816** [comment]
For ScanNet, the instructions are at [ScanNet Data](https://github.com/daveredrum/ScanRefer/blob/master/data/scannet/README.md). For GLoVE embedding, it is hosted not by us, you might need proxy to download it, although it is not actually needed and might not need to be downloaded.
